<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/books.php");
	include("$currDir/books_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('books');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "books";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`books`.`id`" => "id",
		"`books`.`ISBN`" => "ISBN",
		"`books`.`Titulo_do_Livro`" => "Titulo_do_Livro",
		"IF(    CHAR_LENGTH(`Types1`.`Name`), CONCAT_WS('',   `Types1`.`Name`), '') /* Gênero do Livro */" => "Gênero_do_Livro",
		"`books`.`Autor_do_Livro`" => "Autor_do_Livro",
		"`books`.`Quantidade`" => "Quantidade",
		"if(`books`.`Data_de_Aquisição`,date_format(`books`.`Data_de_Aquisição`,'%d/%m/%Y'),'')" => "Data_de_Aquisição",
		"`books`.`Edição`" => "Edição",
		"`books`.`Estante`" => "Estante",
		"`books`.`Prateleira`" => "Prateleira",
		"`books`.`Editora`" => "Editora"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`books`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Types1`.`Name`',
		5 => 5,
		6 => '`books`.`Quantidade`',
		7 => '`books`.`Data_de_Aquisição`',
		8 => 8,
		9 => '`books`.`Estante`',
		10 => '`books`.`Prateleira`',
		11 => 11
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`books`.`id`" => "id",
		"`books`.`ISBN`" => "ISBN",
		"`books`.`Titulo_do_Livro`" => "Titulo_do_Livro",
		"IF(    CHAR_LENGTH(`Types1`.`Name`), CONCAT_WS('',   `Types1`.`Name`), '') /* Gênero do Livro */" => "Gênero_do_Livro",
		"`books`.`Autor_do_Livro`" => "Autor_do_Livro",
		"`books`.`Quantidade`" => "Quantidade",
		"if(`books`.`Data_de_Aquisição`,date_format(`books`.`Data_de_Aquisição`,'%d/%m/%Y'),'')" => "Data_de_Aquisição",
		"`books`.`Edição`" => "Edição",
		"`books`.`Estante`" => "Estante",
		"`books`.`Prateleira`" => "Prateleira",
		"`books`.`Editora`" => "Editora"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`books`.`id`" => "ID",
		"`books`.`ISBN`" => "ISBN",
		"`books`.`Titulo_do_Livro`" => "Titulo do Livro",
		"IF(    CHAR_LENGTH(`Types1`.`Name`), CONCAT_WS('',   `Types1`.`Name`), '') /* Gênero do Livro */" => "Gênero do Livro",
		"`books`.`Autor_do_Livro`" => "Autor do Livro",
		"`books`.`Quantidade`" => "Quantidade",
		"`books`.`Data_de_Aquisição`" => "Data de Aquisição",
		"`books`.`Edição`" => "Edição",
		"`books`.`Estante`" => "Estante",
		"`books`.`Prateleira`" => "Prateleira",
		"`books`.`Editora`" => "Editora"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`books`.`id`" => "id",
		"`books`.`ISBN`" => "ISBN",
		"`books`.`Titulo_do_Livro`" => "Titulo_do_Livro",
		"IF(    CHAR_LENGTH(`Types1`.`Name`), CONCAT_WS('',   `Types1`.`Name`), '') /* Gênero do Livro */" => "Gênero_do_Livro",
		"`books`.`Autor_do_Livro`" => "Autor_do_Livro",
		"`books`.`Quantidade`" => "Quantidade",
		"if(`books`.`Data_de_Aquisição`,date_format(`books`.`Data_de_Aquisição`,'%d/%m/%Y'),'')" => "Data_de_Aquisição",
		"`books`.`Edição`" => "Edição",
		"`books`.`Estante`" => "Estante",
		"`books`.`Prateleira`" => "Prateleira",
		"`books`.`Editora`" => "Editora"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'Gênero_do_Livro' => 'Gênero do Livro');

	$x->QueryFrom = "`books` LEFT JOIN `Types` as Types1 ON `Types1`.`id`=`books`.`Gênero_do_Livro` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "books_view.php";
	$x->RedirectAfterInsert = "books_view.php?SelectedID=#ID#";
	$x->TableTitle = "Livros";
	$x->TableIcon = "resources/table_icons/books.png";
	$x->PrimaryKey = "`books`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 80, 150, 150);
	$x->ColCaption = array("ISBN", "Titulo do Livro", "Gênero do Livro", "Autor do Livro", "Quantidade", "Data de Aquisição", "Edição", "Estante", "Prateleira", "Editora");
	$x->ColFieldName = array('ISBN', 'Titulo_do_Livro', 'Gênero_do_Livro', 'Autor_do_Livro', 'Quantidade', 'Data_de_Aquisição', 'Edição', 'Estante', 'Prateleira', 'Editora');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

	// template paths below are based on the app main directory
	$x->Template = 'templates/books_templateTV.html';
	$x->SelectedTemplate = 'templates/books_templateTVS.html';
	$x->TemplateDV = 'templates/books_templateDV.html';
	$x->TemplateDVP = 'templates/books_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `books`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='books' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `books`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='books' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`books`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: books_init
	$render=TRUE;
	if(function_exists('books_init')){
		$args=array();
		$render=books_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: books_header
	$headerCode='';
	if(function_exists('books_header')){
		$args=array();
		$headerCode=books_header($x->ContentType, getMemberInfo(), $args);
	}
	if(!$headerCode){
		include_once("$currDir/header.php");
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: books_footer
	$footerCode='';
	if(function_exists('books_footer')){
		$args=array();
		$footerCode=books_footer($x->ContentType, getMemberInfo(), $args);
	}
	if(!$footerCode){
		include_once("$currDir/footer.php");
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>
