<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('Book_Issue');
	if(!$table_perms[0]){ die('// Access denied!'); }

	$mfk=$_GET['mfk'];
	$id=makeSafe($_GET['id']);
	$rnd1=intval($_GET['rnd1']); if(!$rnd1) $rnd1='';

	if(!$mfk){
		die('// No js code available!');
	}

	switch($mfk){

		case 'Member':
			if(!$id){
				?>
				$('Number<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				<?php
				break;
			}
			$res = sql("SELECT `Users`.`id` as 'id', `Users`.`RA_do_Aluno` as 'RA_do_Aluno', `Users`.`Name` as 'Name', `Users`.`Contato` as 'Contato', `Users`.`Ano` as 'Ano' FROM `Users`  WHERE `Users`.`id`='$id' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#Number<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['RA_do_Aluno']))); ?>&nbsp;');
			<?php
			break;

		case 'Book_Number':
			if(!$id){
				?>
				$('Titulo_do_Livro<?php echo $rnd1; ?>').innerHTML='&nbsp;';
				<?php
				break;
			}
			$res = sql("SELECT `books`.`id` as 'id', `books`.`ISBN` as 'ISBN', `books`.`Titulo_do_Livro` as 'Titulo_do_Livro', IF(    CHAR_LENGTH(`Types1`.`Name`), CONCAT_WS('',   `Types1`.`Name`), '') as 'Gênero_do_Livro', `books`.`Autor_do_Livro` as 'Autor_do_Livro', `books`.`Quantidade` as 'Quantidade', if(`books`.`Data_de_Aquisição`,date_format(`books`.`Data_de_Aquisição`,'%d/%m/%Y'),'') as 'Data_de_Aquisição', `books`.`Edição` as 'Edição', `books`.`Estante` as 'Estante', `books`.`Prateleira` as 'Prateleira', `books`.`Editora` as 'Editora' FROM `books` LEFT JOIN `Types` as Types1 ON `Types1`.`id`=`books`.`Gênero_do_Livro`  WHERE `books`.`id`='$id' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#Titulo_do_Livro<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['Titulo_do_Livro']))); ?>&nbsp;');
			<?php
			break;


	}

?>