<?php

// Data functions (insert, update, delete, form) for table books

// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

function books_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('books');
	if(!$arrPerm[1]){
		return false;
	}

	$data['ISBN'] = makeSafe($_REQUEST['ISBN']);
		if($data['ISBN'] == empty_lookup_value){ $data['ISBN'] = ''; }
	$data['Titulo_do_Livro'] = makeSafe($_REQUEST['Titulo_do_Livro']);
		if($data['Titulo_do_Livro'] == empty_lookup_value){ $data['Titulo_do_Livro'] = ''; }
	$data['Gênero_do_Livro'] = makeSafe($_REQUEST['Gênero_do_Livro']);
		if($data['Gênero_do_Livro'] == empty_lookup_value){ $data['Gênero_do_Livro'] = ''; }
	$data['Autor_do_Livro'] = makeSafe($_REQUEST['Autor_do_Livro']);
		if($data['Autor_do_Livro'] == empty_lookup_value){ $data['Autor_do_Livro'] = ''; }
	$data['Quantidade'] = makeSafe($_REQUEST['Quantidade']);
		if($data['Quantidade'] == empty_lookup_value){ $data['Quantidade'] = ''; }
	$data['Data_de_Aquisição'] = intval($_REQUEST['Data_de_AquisiçãoYear']) . '-' . intval($_REQUEST['Data_de_AquisiçãoMonth']) . '-' . intval($_REQUEST['Data_de_AquisiçãoDay']);
	$data['Data_de_Aquisição'] = parseMySQLDate($data['Data_de_Aquisição'], '1');
	$data['Edição'] = makeSafe($_REQUEST['Edição']);
		if($data['Edição'] == empty_lookup_value){ $data['Edição'] = ''; }
	$data['Estante'] = makeSafe($_REQUEST['Estante']);
		if($data['Estante'] == empty_lookup_value){ $data['Estante'] = ''; }
	$data['Prateleira'] = makeSafe($_REQUEST['Prateleira']);
		if($data['Prateleira'] == empty_lookup_value){ $data['Prateleira'] = ''; }
	$data['Editora'] = makeSafe($_REQUEST['Editora']);
		if($data['Editora'] == empty_lookup_value){ $data['Editora'] = ''; }
	if($data['Estante'] == '') $data['Estante'] = "0.00";

	// hook: books_before_insert
	if(function_exists('books_before_insert')){
		$args=array();
		if(!books_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `books` set       `ISBN`=' . (($data['ISBN'] !== '' && $data['ISBN'] !== NULL) ? "'{$data['ISBN']}'" : 'NULL') . ', `Titulo_do_Livro`=' . (($data['Titulo_do_Livro'] !== '' && $data['Titulo_do_Livro'] !== NULL) ? "'{$data['Titulo_do_Livro']}'" : 'NULL') . ', `Gênero_do_Livro`=' . (($data['Gênero_do_Livro'] !== '' && $data['Gênero_do_Livro'] !== NULL) ? "'{$data['Gênero_do_Livro']}'" : 'NULL') . ', `Autor_do_Livro`=' . (($data['Autor_do_Livro'] !== '' && $data['Autor_do_Livro'] !== NULL) ? "'{$data['Autor_do_Livro']}'" : 'NULL') . ', `Quantidade`=' . (($data['Quantidade'] !== '' && $data['Quantidade'] !== NULL) ? "'{$data['Quantidade']}'" : 'NULL') . ', `Data_de_Aquisição`=' . (($data['Data_de_Aquisição'] !== '' && $data['Data_de_Aquisição'] !== NULL) ? "'{$data['Data_de_Aquisição']}'" : 'NULL') . ', `Edição`=' . (($data['Edição'] !== '' && $data['Edição'] !== NULL) ? "'{$data['Edição']}'" : 'NULL') . ', `Estante`=' . (($data['Estante'] !== '' && $data['Estante'] !== NULL) ? "'{$data['Estante']}'" : 'NULL') . ', `Prateleira`=' . (($data['Prateleira'] !== '' && $data['Prateleira'] !== NULL) ? "'{$data['Prateleira']}'" : 'NULL') . ', `Editora`=' . (($data['Editora'] !== '' && $data['Editora'] !== NULL) ? "'{$data['Editora']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"books_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: books_after_insert
	if(function_exists('books_after_insert')){
		$res = sql("select * from `books` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!books_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('books', $recID, getLoggedMemberID());

	return $recID;
}

function books_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('books');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='books' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='books' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: books_before_delete
	if(function_exists('books_before_delete')){
		$args=array();
		if(!books_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	// child table: Book_Issue
	$res = sql("select `id` from `books` where `id`='$selected_id'", $eo);
	$id = db_fetch_row($res);
	$rires = sql("select count(1) from `Book_Issue` where `Book_Number`='".addslashes($id[0])."'", $eo);
	$rirow = db_fetch_row($rires);
	if($rirow[0] && !$AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["couldn't delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Book_Issue", $RetMsg);
		return $RetMsg;
	}elseif($rirow[0] && $AllowDeleteOfParents && !$skipChecks){
		$RetMsg = $Translation["confirm delete"];
		$RetMsg = str_replace("<RelatedRecords>", $rirow[0], $RetMsg);
		$RetMsg = str_replace("<TableName>", "Book_Issue", $RetMsg);
		$RetMsg = str_replace("<Delete>", "<input type=\"button\" class=\"button\" value=\"".$Translation['yes']."\" onClick=\"window.location='books_view.php?SelectedID=".urlencode($selected_id)."&delete_x=1&confirmed=1';\">", $RetMsg);
		$RetMsg = str_replace("<Cancel>", "<input type=\"button\" class=\"button\" value=\"".$Translation['no']."\" onClick=\"window.location='books_view.php?SelectedID=".urlencode($selected_id)."';\">", $RetMsg);
		return $RetMsg;
	}

	sql("delete from `books` where `id`='$selected_id'", $eo);

	// hook: books_after_delete
	if(function_exists('books_after_delete')){
		$args=array();
		books_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='books' and pkValue='$selected_id'", $eo);
}

function books_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('books');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='books' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='books' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['ISBN'] = makeSafe($_REQUEST['ISBN']);
		if($data['ISBN'] == empty_lookup_value){ $data['ISBN'] = ''; }
	$data['Titulo_do_Livro'] = makeSafe($_REQUEST['Titulo_do_Livro']);
		if($data['Titulo_do_Livro'] == empty_lookup_value){ $data['Titulo_do_Livro'] = ''; }
	$data['Gênero_do_Livro'] = makeSafe($_REQUEST['Gênero_do_Livro']);
		if($data['Gênero_do_Livro'] == empty_lookup_value){ $data['Gênero_do_Livro'] = ''; }
	$data['Autor_do_Livro'] = makeSafe($_REQUEST['Autor_do_Livro']);
		if($data['Autor_do_Livro'] == empty_lookup_value){ $data['Autor_do_Livro'] = ''; }
	$data['Quantidade'] = makeSafe($_REQUEST['Quantidade']);
		if($data['Quantidade'] == empty_lookup_value){ $data['Quantidade'] = ''; }
	$data['Data_de_Aquisição'] = intval($_REQUEST['Data_de_AquisiçãoYear']) . '-' . intval($_REQUEST['Data_de_AquisiçãoMonth']) . '-' . intval($_REQUEST['Data_de_AquisiçãoDay']);
	$data['Data_de_Aquisição'] = parseMySQLDate($data['Data_de_Aquisição'], '1');
	$data['Edição'] = makeSafe($_REQUEST['Edição']);
		if($data['Edição'] == empty_lookup_value){ $data['Edição'] = ''; }
	$data['Estante'] = makeSafe($_REQUEST['Estante']);
		if($data['Estante'] == empty_lookup_value){ $data['Estante'] = ''; }
	$data['Prateleira'] = makeSafe($_REQUEST['Prateleira']);
		if($data['Prateleira'] == empty_lookup_value){ $data['Prateleira'] = ''; }
	$data['Editora'] = makeSafe($_REQUEST['Editora']);
		if($data['Editora'] == empty_lookup_value){ $data['Editora'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: books_before_update
	if(function_exists('books_before_update')){
		$args=array();
		if(!books_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `books` set       `ISBN`=' . (($data['ISBN'] !== '' && $data['ISBN'] !== NULL) ? "'{$data['ISBN']}'" : 'NULL') . ', `Titulo_do_Livro`=' . (($data['Titulo_do_Livro'] !== '' && $data['Titulo_do_Livro'] !== NULL) ? "'{$data['Titulo_do_Livro']}'" : 'NULL') . ', `Gênero_do_Livro`=' . (($data['Gênero_do_Livro'] !== '' && $data['Gênero_do_Livro'] !== NULL) ? "'{$data['Gênero_do_Livro']}'" : 'NULL') . ', `Autor_do_Livro`=' . (($data['Autor_do_Livro'] !== '' && $data['Autor_do_Livro'] !== NULL) ? "'{$data['Autor_do_Livro']}'" : 'NULL') . ', `Quantidade`=' . (($data['Quantidade'] !== '' && $data['Quantidade'] !== NULL) ? "'{$data['Quantidade']}'" : 'NULL') . ', `Data_de_Aquisição`=' . (($data['Data_de_Aquisição'] !== '' && $data['Data_de_Aquisição'] !== NULL) ? "'{$data['Data_de_Aquisição']}'" : 'NULL') . ', `Edição`=' . (($data['Edição'] !== '' && $data['Edição'] !== NULL) ? "'{$data['Edição']}'" : 'NULL') . ', `Estante`=' . (($data['Estante'] !== '' && $data['Estante'] !== NULL) ? "'{$data['Estante']}'" : 'NULL') . ', `Prateleira`=' . (($data['Prateleira'] !== '' && $data['Prateleira'] !== NULL) ? "'{$data['Prateleira']}'" : 'NULL') . ', `Editora`=' . (($data['Editora'] !== '' && $data['Editora'] !== NULL) ? "'{$data['Editora']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="books_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: books_after_update
	if(function_exists('books_after_update')){
		$res = sql("SELECT * FROM `books` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!books_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='books' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function books_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('books');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_Gênero_do_Livro = thisOr(undo_magic_quotes($_REQUEST['filterer_Gênero_do_Livro']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Gênero_do_Livro
	$combo_Gênero_do_Livro = new DataCombo;
	// combobox: Data_de_Aquisição
	$combo_Data_de_Aquisição = new DateCombo;
	$combo_Data_de_Aquisição->DateFormat = "mdy";
	$combo_Data_de_Aquisição->MinYear = 1900;
	$combo_Data_de_Aquisição->MaxYear = 2100;
	$combo_Data_de_Aquisição->DefaultDate = parseMySQLDate('1', '1');
	$combo_Data_de_Aquisição->MonthNames = $Translation['month names'];
	$combo_Data_de_Aquisição->NamePrefix = 'Data_de_Aquisição';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='books' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='books' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `books` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'books_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_Gênero_do_Livro->SelectedData = $row['Gênero_do_Livro'];
		$combo_Data_de_Aquisição->DefaultDate = $row['Data_de_Aquisição'];
	}else{
		$combo_Gênero_do_Livro->SelectedData = $filterer_Gênero_do_Livro;
	}
	$combo_Gênero_do_Livro->HTML = '<span id="Gênero_do_Livro-container' . $rnd1 . '"></span><input type="hidden" name="Gênero_do_Livro" id="Gênero_do_Livro' . $rnd1 . '" value="' . html_attr($combo_Gênero_do_Livro->SelectedData) . '">';
	$combo_Gênero_do_Livro->MatchText = '<span id="Gênero_do_Livro-container-readonly' . $rnd1 . '"></span><input type="hidden" name="Gênero_do_Livro" id="Gênero_do_Livro' . $rnd1 . '" value="' . html_attr($combo_Gênero_do_Livro->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_Gênero_do_Livro__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['Gênero_do_Livro'] : $filterer_Gênero_do_Livro); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(Gênero_do_Livro_reload__RAND__) == 'function') Gênero_do_Livro_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function Gênero_do_Livro_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#Gênero_do_Livro-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_Gênero_do_Livro__RAND__.value, t: 'books', f: 'Gênero_do_Livro' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="Gênero_do_Livro"]').val(resp.results[0].id);
							$j('[id=Gênero_do_Livro-container-readonly__RAND__]').html('<span id="Gênero_do_Livro-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Types_view_parent]').hide(); }else{ $j('.btn[id=Types_view_parent]').show(); }


							if(typeof(Gênero_do_Livro_update_autofills__RAND__) == 'function') Gênero_do_Livro_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'books', f: 'Gênero_do_Livro' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_Gênero_do_Livro__RAND__.value = e.added.id;
				AppGini.current_Gênero_do_Livro__RAND__.text = e.added.text;
				$j('[name="Gênero_do_Livro"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Types_view_parent]').hide(); }else{ $j('.btn[id=Types_view_parent]').show(); }


				if(typeof(Gênero_do_Livro_update_autofills__RAND__) == 'function') Gênero_do_Livro_update_autofills__RAND__();
			});

			if(!$j("#Gênero_do_Livro-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_Gênero_do_Livro__RAND__.value, t: 'books', f: 'Gênero_do_Livro' },
					success: function(resp){
						$j('[name="Gênero_do_Livro"]').val(resp.results[0].id);
						$j('[id=Gênero_do_Livro-container-readonly__RAND__]').html('<span id="Gênero_do_Livro-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Types_view_parent]').hide(); }else{ $j('.btn[id=Types_view_parent]').show(); }

						if(typeof(Gênero_do_Livro_update_autofills__RAND__) == 'function') Gênero_do_Livro_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_Gênero_do_Livro__RAND__.value, t: 'books', f: 'Gênero_do_Livro' },
				success: function(resp){
					$j('[id=Gênero_do_Livro-container__RAND__], [id=Gênero_do_Livro-container-readonly__RAND__]').html('<span id="Gênero_do_Livro-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Types_view_parent]').hide(); }else{ $j('.btn[id=Types_view_parent]').show(); }

					if(typeof(Gênero_do_Livro_update_autofills__RAND__) == 'function') Gênero_do_Livro_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/books_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/books_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Book details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return books_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return books_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return books_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#ISBN').replaceWith('<div class=\"form-control-static\" id=\"ISBN\">' + (jQuery('#ISBN').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Titulo_do_Livro').replaceWith('<div class=\"form-control-static\" id=\"Titulo_do_Livro\">' + (jQuery('#Titulo_do_Livro').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Gênero_do_Livro').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Gênero_do_Livro_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#Autor_do_Livro').replaceWith('<div class=\"form-control-static\" id=\"Autor_do_Livro\">' + (jQuery('#Autor_do_Livro').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Quantidade').replaceWith('<div class=\"form-control-static\" id=\"Quantidade\">' + (jQuery('#Quantidade').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Data_de_Aquisição').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Data_de_AquisiçãoDay, #Data_de_AquisiçãoMonth, #Data_de_AquisiçãoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Edição').replaceWith('<div class=\"form-control-static\" id=\"Edição\">' + (jQuery('#Edição').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Estante').replaceWith('<div class=\"form-control-static\" id=\"Estante\">' + (jQuery('#Estante').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Prateleira').replaceWith('<div class=\"form-control-static\" id=\"Prateleira\">' + (jQuery('#Prateleira').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Editora').replaceWith('<div class=\"form-control-static\" id=\"Editora\">' + (jQuery('#Editora').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Gênero_do_Livro)%%>', $combo_Gênero_do_Livro->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Gênero_do_Livro)%%>', $combo_Gênero_do_Livro->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(Gênero_do_Livro)%%>', urlencode($combo_Gênero_do_Livro->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(Data_de_Aquisição)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Data_de_Aquisição->GetHTML(true) . '</div>' : $combo_Data_de_Aquisição->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Data_de_Aquisição)%%>', $combo_Data_de_Aquisição->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'Gênero_do_Livro' => array('Types', 'Gênero do Livro'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(ISBN)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Titulo_do_Livro)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Gênero_do_Livro)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Autor_do_Livro)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Quantidade)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Data_de_Aquisição)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Edição)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Estante)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Prateleira)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Editora)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(ISBN)%%>', safe_html($urow['ISBN']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(ISBN)%%>', html_attr($row['ISBN']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ISBN)%%>', urlencode($urow['ISBN']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Titulo_do_Livro)%%>', safe_html($urow['Titulo_do_Livro']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Titulo_do_Livro)%%>', html_attr($row['Titulo_do_Livro']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Titulo_do_Livro)%%>', urlencode($urow['Titulo_do_Livro']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Gênero_do_Livro)%%>', safe_html($urow['Gênero_do_Livro']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Gênero_do_Livro)%%>', html_attr($row['Gênero_do_Livro']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Gênero_do_Livro)%%>', urlencode($urow['Gênero_do_Livro']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Autor_do_Livro)%%>', safe_html($urow['Autor_do_Livro']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Autor_do_Livro)%%>', html_attr($row['Autor_do_Livro']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Autor_do_Livro)%%>', urlencode($urow['Autor_do_Livro']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Quantidade)%%>', safe_html($urow['Quantidade']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Quantidade)%%>', html_attr($row['Quantidade']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Quantidade)%%>', urlencode($urow['Quantidade']), $templateCode);
		$templateCode = str_replace('<%%VALUE(Data_de_Aquisição)%%>', @date('d/m/Y', @strtotime(html_attr($row['Data_de_Aquisição']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Data_de_Aquisição)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['Data_de_Aquisição'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Edição)%%>', safe_html($urow['Edição']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Edição)%%>', html_attr($row['Edição']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Edição)%%>', urlencode($urow['Edição']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Estante)%%>', safe_html($urow['Estante']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Estante)%%>', html_attr($row['Estante']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estante)%%>', urlencode($urow['Estante']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Prateleira)%%>', safe_html($urow['Prateleira']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Prateleira)%%>', html_attr($row['Prateleira']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Prateleira)%%>', urlencode($urow['Prateleira']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(Editora)%%>', safe_html($urow['Editora']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Editora)%%>', html_attr($row['Editora']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Editora)%%>', urlencode($urow['Editora']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(ISBN)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(ISBN)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Titulo_do_Livro)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Titulo_do_Livro)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Gênero_do_Livro)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Gênero_do_Livro)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Autor_do_Livro)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Autor_do_Livro)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Quantidade)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Quantidade)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Data_de_Aquisição)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Data_de_Aquisição)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Edição)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Edição)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Estante)%%>', '0.00', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Estante)%%>', urlencode('0.00'), $templateCode);
		$templateCode = str_replace('<%%VALUE(Prateleira)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Prateleira)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(Editora)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Editora)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('books');
	if($selected_id){
		$jdata = get_joined_record('books', $selected_id);
		if($jdata === false) $jdata = get_defaults('books');
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata))
	);
	$templateCode .= loadView('books-ajax-cache', $cache_data);

	// hook: books_dv
	if(function_exists('books_dv')){
		$args=array();
		books_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>