<?php

// Data functions (insert, update, delete, form) for table Magazines

// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

function Magazines_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('Magazines');
	if(!$arrPerm[1]){
		return false;
	}

	$data['Gênero_da_Revista'] = makeSafe($_REQUEST['Gênero_da_Revista']);
		if($data['Gênero_da_Revista'] == empty_lookup_value){ $data['Gênero_da_Revista'] = ''; }

	$data['Nome_da_Revista'] = makeSafe($_REQUEST['Nome_da_Revista']);
		if($data['Nome_da_Revista'] == empty_lookup_value){ $data['Nome_da_Revista'] = ''; }

	$data['Data_de_Publicação'] = intval($_REQUEST['Data_de_PublicaçãotDay']) . '-' . intval($_REQUEST['Data_de_PublicaçãoMonth']) . '-' . intval($_REQUEST['Data_de_PublicaçãoYear']);
	$data['Data_de_Publicação'] = parseMySQLDate($data['Data_de_Publicação'], '');

	$data['Data_de_Recebimento'] = intval($_REQUEST['Data_de_RecebimentoDay']) . '-' . intval($_REQUEST['Data_de_RecebimentoMonth']) . '-' . intval($_REQUEST['Data_de_RecebimentoYear']);
	$data['Data_de_Recebimento'] = parseMySQLDate($data['Data_de_Recebimento'], '');

	$data['Editora'] = makeSafe($_REQUEST['Editora']);
		if($data['Editora'] == empty_lookup_value){ $data['Editora'] = ''; }

	// hook: Magazines_before_insert
	if(function_exists('Magazines_before_insert')){
		$args=array();
		if(!Magazines_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `Magazines` set

	`Gênero_da_Revista`=' . (($data['Gênero_da_Revista'] !== '' && $data['Gênero_da_Revista'] !== NULL) ? "'{$data['Gênero_da_Revista']}'" : 'NULL') . ',
	`Nome_da_Revista`=' . (($data['Nome_da_Revista'] !== '' && $data['Nome_da_Revista'] !== NULL) ? "'{$data['Nome_da_Revista']}'" : 'NULL') . ',
	`Data_de_Publicação`=' . (($data['Data_de_Publicação'] !== '' && $data['Data_de_Publicação'] !== NULL) ? "'{$data['Data_de_Publicação']}'" : 'NULL') . ',
	`Data_de_Recebimento`=' . (($data['Data_de_Recebimento'] !== '' && $data['Data_de_Recebimento'] !== NULL) ? "'{$data['Data_de_Recebimento']}'" : 'NULL') . ',
	`Editora`=' . (($data['Editora'] !== '' && $data['Editora'] !== NULL) ? "'{$data['Editora']}'" : 'NULL'), $o);

	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"Magazines_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: Magazines_after_insert
	if(function_exists('Magazines_after_insert')){
		$res = sql("select * from `Magazines` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Magazines_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Magazines', $recID, getLoggedMemberID());

	return $recID;
}

function Magazines_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Magazines');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Magazines' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Magazines' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Magazines_before_delete
	if(function_exists('Magazines_before_delete')){
		$args=array();
		if(!Magazines_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Magazines` where `id`='$selected_id'", $eo);

	// hook: Magazines_after_delete
	if(function_exists('Magazines_after_delete')){
		$args=array();
		Magazines_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Magazines' and pkValue='$selected_id'", $eo);
}

function Magazines_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Magazines');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Magazines' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Magazines' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['Gênero_da_Revista'] = makeSafe($_REQUEST['Gênero_da_Revista']);
		if($data['Gênero_da_Revista'] == empty_lookup_value){ $data['Gênero_da_Revista'] = ''; }

	$data['Nome_da_Revista'] = makeSafe($_REQUEST['Nome_da_Revista']);
		if($data['Nome_da_Revista'] == empty_lookup_value){ $data['Nome_da_Revista'] = ''; }

	$data['Data_de_Publicação'] = intval($_REQUEST['Data_de_PublicaçãoDay']) . '-' . intval($_REQUEST['Data_de_PublicaçãoMonth']) . '-' . intval($_REQUEST['Data_de_PublicaçãoYear']);
	$data['Data_de_Publicação'] = parseMySQLDate($data['Data_de_Publicação'], '');

	$data['Data_de_Recebimento'] = intval($_REQUEST['Data_de_RecebimentoDay']) . '-' . intval($_REQUEST['Data_de_RecebimentoMonth']) . '-' . intval($_REQUEST['Data_de_RecebimentoYear']);
	$data['Data_de_Recebimento'] = parseMySQLDate($data['Data_de_Recebimento'], '');

	$data['Editora'] = makeSafe($_REQUEST['Editora']);
		if($data['Editora'] == empty_lookup_value){ $data['Editora'] = ''; }
	$data['selectedID']=makeSafe($selected_id);

	// hook: Magazines_before_update
	if(function_exists('Magazines_before_update')){
		$args=array();
		if(!Magazines_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `Magazines` set

	`Gênero_da_Revista`=' . (($data['Gênero_da_Revista'] !== '' && $data['Gênero_da_Revista'] !== NULL) ? "'{$data['Gênero_da_Revista']}'" : 'NULL') . ',
	`Nome_da_Revista`=' . (($data['Nome_da_Revista'] !== '' && $data['Nome_da_Revista'] !== NULL) ? "'{$data['Name']}'" : 'NULL') . ',
	`Data_de_Publicação`=' . (($data['Data_de_Publicação'] !== '' && $data['Data_de_Publicação'] !== NULL) ? "'{$data['Data_de_Publicação']}'" : 'NULL') . ',
	`Data_de_Recebimento`=' . (($data['Data_de_Recebimento'] !== '' && $data['Data_de_Recebimento'] !== NULL) ? "'{$data['Data_de_Recebimento']}'" : 'NULL') . ',
	`Editora`=' . (($data['Editora'] !== '' && $data['Editora'] !== NULL) ? "'{$data['Editora']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);

	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="Magazines_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}

	if(function_exists('Magazines_after_update')){
		$res = sql("SELECT * FROM `Magazines` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Magazines_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='Magazines' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function Magazines_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Magazines');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}


	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: Data_de_Publicação
	$combo_Data_de_Publicação = new DateCombo;
	$combo_Data_de_Publicação->DateFormat = "dmy";
	$combo_Data_de_Publicação->MinYear = 1900;
	$combo_Data_de_Publicação->MaxYear = 2100;
	$combo_Data_de_Publicação->DefaultDate = parseMySQLDate('', '');
	$combo_Data_de_Publicação->MonthNames = $Translation['month names'];
	$combo_Data_de_Publicação->NamePrefix = 'Data_de_Publicação';
	// combobox: Data_de_Recebimento
	$combo_Data_de_Recebimento = new DateCombo;
	$combo_Data_de_Recebimento->DateFormat = "dmy";
	$combo_Data_de_Recebimento->MinYear = 1900;
	$combo_Data_de_Recebimento->MaxYear = 2100;
	$combo_Data_de_Recebimento->DefaultDate = parseMySQLDate('', '');
	$combo_Data_de_Recebimento->MonthNames = $Translation['month names'];
	$combo_Data_de_Recebimento->NamePrefix = 'Data_de_Recebimento';

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Magazines' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Magazines' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `Magazines` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'Magazines_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_Data_de_Publicação->DefaultDate = $row['Data_de_Publicação'];
		$combo_Data_de_Recebimento->DefaultDate = $row['Data_de_Recebimento'];
	}else{
	}

	ob_start();
	?>

	<script>
		// initial lookup values

		jQuery(function() {
			setTimeout(function(){
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Magazines_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Magazines_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Magazine details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Magazines_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Magazines_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Magazines_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#Gênero_da_Revista').replaceWith('<div class=\"form-control-static\" id=\"Gênero_da_Revista\">' + (jQuery('#Gênero_da_Revista').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Nome_da_Revista').replaceWith('<div class=\"form-control-static\" id=\"Nome_da_Revista\">' + (jQuery('#Nome_da_Revista').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#Data_de_Publicação').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Data_de_PublicaçãoDay, #Data_de_PublicaçãoMonth, #Data_de_PublicaçãoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Data_de_Recebimento').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#Data_de_RecebimentoDay, #Data_de_RecebimentoMonth, #Data_de_RecebimentoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#Editora').replaceWith('<div class=\"form-control-static\" id=\"Editora\">' + (jQuery('#Editora').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(Data_de_Publicação)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Data_de_Publicação->GetHTML(true) . '</div>' : $combo_Data_de_Publicação->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Data_de_Publicação)%%>', $combo_Data_de_Publicação->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(Data_de_Recebimento)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_Data_de_Recebimento->GetHTML(true) . '</div>' : $combo_Data_de_Recebimento->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(Data_de_Recebimento)%%>', $combo_Data_de_Recebimento->GetHTML(true), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array();
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Gênero_da_Revista)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Nome_da_Revista)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Data_de_Publicação)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Data_de_Recebimento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(Editora)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);

		if( $dvprint) $templateCode = str_replace('<%%VALUE(Gênero_da_Revista)%%>', safe_html($urow['Gênero_da_Revista']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Gênero_da_Revista)%%>', html_attr($row['Gênero_da_Revista']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Gênero_da_Revista)%%>', urlencode($urow['Gênero_da_Revista']), $templateCode);

		if( $dvprint) $templateCode = str_replace('<%%VALUE(Nome_da_Revista)%%>', safe_html($urow['Nome_da_Revista']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Nome_da_Revista)%%>', html_attr($row['Nome_da_Revista']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome_da_Revista)%%>', urlencode($urow['Nome_da_Revista']), $templateCode);

		$templateCode = str_replace('<%%VALUE(Data_de_Publicação)%%>', @date('d/m/Y', @strtotime(html_attr($row['Data_de_Publicação']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Data_de_Publicação)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['Data_de_Publicação'])))), $templateCode);

		$templateCode = str_replace('<%%VALUE(Data_de_Recebimento)%%>', @date('d/m/Y', @strtotime(html_attr($row['Data_de_Recebimento']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Data_de_Recebimento)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['Data_de_Recebimento'])))), $templateCode);

		if( $dvprint) $templateCode = str_replace('<%%VALUE(Editora)%%>', safe_html($urow['Editora']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(Editora)%%>', html_attr($row['Editora']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Editora)%%>', urlencode($urow['Editora']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);

		$templateCode = str_replace('<%%VALUE(Gênero_da_Revista)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Gênero_da_Revista)%%>', urlencode(''), $templateCode);

		$templateCode = str_replace('<%%VALUE(Nome_da_Revista)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Nome_da_Revista)%%>', urlencode(''), $templateCode);

		$templateCode = str_replace('<%%VALUE(Data_de_Publicação)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Data_de_Publicação)%%>', urlencode(''), $templateCode);

		$templateCode = str_replace('<%%VALUE(Data_de_Recebimento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Data_de_Recebimento)%%>', urlencode(''), $templateCode);
		
		$templateCode = str_replace('<%%VALUE(Editora)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(Editora)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Magazines');
	if($selected_id){
		$jdata = get_joined_record('Magazines', $selected_id);
		if($jdata === false) $jdata = get_defaults('Magazines');
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata))
	);
	$templateCode .= loadView('Magazines-ajax-cache', $cache_data);

	// hook: Magazines_dv
	if(function_exists('Magazines_dv')){
		$args=array();
		Magazines_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>
