<?php
// This script and data application were generated by AppGini 5.70
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Users.php");
	include("$currDir/Users_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Users');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Users";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(
		"`Users`.`id`" => "id",
		"`Users`.`RA_do_Aluno`" => "RA_do_Aluno",
		"`Users`.`Name`" => "Name",
		"`Users`.`Contato`" => "Contato",
		"`Users`.`Ano`" => "Ano"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(
		1 => '`Users`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => '`Users`.`Ano`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(
		"`Users`.`id`" => "id",
		"`Users`.`RA_do_Aluno`" => "RA_do_Aluno",
		"`Users`.`Name`" => "Name",
		"`Users`.`Contato`" => "Contato",
		"`Users`.`Ano`" => "Ano"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(
		"`Users`.`id`" => "ID",
		"`Users`.`RA_do_Aluno`" => "RA do Aluno",
		"`Users`.`Name`" => "Name",
		"`Users`.`Contato`" => "Contato",
		"`Users`.`Ano`" => "Ano"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(
		"`Users`.`id`" => "id",
		"`Users`.`RA_do_Aluno`" => "RA_do_Aluno",
		"`Users`.`Name`" => "Name",
		"`Users`.`Contato`" => "Contato",
		"`Users`.`Ano`" => "Ano"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Users` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = true;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Users_view.php";
	$x->RedirectAfterInsert = "Users_view.php?SelectedID=#ID#";
	$x->TableTitle = "Alunos";
	$x->TableIcon = "resources/table_icons/group.png";
	$x->PrimaryKey = "`Users`.`id`";

	$x->ColWidth   = array(150, 150, 150, 150);
	$x->ColCaption = array("RA do Aluno", "Name", "Contato", "Ano");
	$x->ColFieldName = array('RA_do_Aluno', 'Name', 'Contato', 'Ano');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Users_templateTV.html';
	$x->SelectedTemplate = 'templates/Users_templateTVS.html';
	$x->TemplateDV = 'templates/Users_templateDV.html';
	$x->TemplateDVP = 'templates/Users_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Users`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Users' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Users`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Users' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Users`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Users_init
	$render=TRUE;
	if(function_exists('Users_init')){
		$args=array();
		$render=Users_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Users_header
	$headerCode='';
	if(function_exists('Users_header')){
		$args=array();
		$headerCode=Users_header($x->ContentType, getMemberInfo(), $args);
	}
	if(!$headerCode){
		include_once("$currDir/header.php");
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Users_footer
	$footerCode='';
	if(function_exists('Users_footer')){
		$args=array();
		$footerCode=Users_footer($x->ContentType, getMemberInfo(), $args);
	}
	if(!$footerCode){
		include_once("$currDir/footer.php");
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>
